### ISSUE TITLE
Clarification Needed on Matrix Multiplication with Trainable Variables in NSC Survival Analysis

### ISSUE THREAD

**Issue by dongin914** [Jeanselme/NeuralSurvivalClustering#1]
Hello,

I am studying survival analysis in South Korea. I came across your paper and code on NSC and have a question that arose from my studies.

My query pertains to the process of going from latent to logOutcome, where tau(time) is concatenated. It seems that latent is a trainable variable. This leads me to wonder, in the process of creating a **representation** positive, if the input is latent, does this mean that the operation involves a matrix multiplication (matmul) of trainable variables?

Typically, as I understand, matrix multiplication is done between constants and trainable variables. However, in this case, the input latent (including added time 't') seems to involve a matmul operation between trainable variables, which is uncommon. If my understanding is correct, what is the significance of having a matmul operation between trainable variables in this context?

Furthermore, I am curious why there is not a direct matmul operation between time 't' and the surv_layers, excluding the latent variable. My understanding is that, in a typical scenario, this would be the usual approach.

I always find your repository to be a great resource in my studies. Thank you for all the help you provide.

Thank you.

**Comment by Jeanselme** [comment]
Hello,

Both the latent representation and the neural network's parameters are learnt during training. This is for more flexibility as one could focus on learning the network's parameters with the time as only input. I agree that this choice is not the only possible. Your proposed alternative would work: we could multiply the input by time. This would be interesting to compare the convergence speed and accuracy of different alternatives.

**Comment by dongin914** [comment]
Thank you for your prompt and kind response.
